name: GNS-PyTorch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.*
  - pytorch-cuda=12.1
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - numpy=1.26.*
  - scipy
  - matplotlib
  - pyyaml
  - yacs
  - h5py
  - pillow
  - tensorboard
  - ipython
  - tensorflow=2.15.*
  - pip
