name: GNS-PyTorch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - pyyaml
  - yacs
  - h5py
  - matplotlib
  - tensorboard
  - pip
  - pip:
      - tensorflow-cpu==2.15.1
